# Generated by Django 6.0.1 on 2026-01-21 00:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_historicalorder_user_order_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReview",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Имя покупателя"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email покупателя"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Ужасно"),
                            (2, "Плохо"),
                            (3, "Нормально"),
                            (4, "Хорошо"),
                            (5, "Отлично"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "advantages",
                    models.TextField(blank=True, verbose_name="Достоинства"),
                ),
                (
                    "disadvantages",
                    models.TextField(blank=True, verbose_name="Недостатки"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрен"),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждённая покупка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата обновления"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="shop.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Отзыв",
                "verbose_name_plural": "historical Отзывы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplier",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="Контактное лицо"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата добавления"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Поставщик",
                "verbose_name_plural": "historical Поставщики",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="Контактное лицо"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suppliers",
                        to="shop.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Имя покупателя"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email покупателя"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Ужасно"),
                            (2, "Плохо"),
                            (3, "Нормально"),
                            (4, "Хорошо"),
                            (5, "Отлично"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "advantages",
                    models.TextField(blank=True, verbose_name="Достоинства"),
                ),
                (
                    "disadvantages",
                    models.TextField(blank=True, verbose_name="Недостатки"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрен"),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждённая покупка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
                "unique_together": {("product", "customer_email")},
            },
        ),
    ]
